### PR TITLE
Save image URL to database

### LINKED ISSUE #4: Save Image Link
#### As a user I want to save a link to an image.

Acceptance criteria:
- [ ] The link is entered through a form.
- [ ] After the form is saved, the link is persisted in the database.

Dependencies:
- Deployment Environment

### PR DESCRIPTION
**Pull request by paulwhite**
Closes #4

### CODE REVIEW

**Comment by bboe** [comment]
Can you add "Fixes #?" in the pull request description please?

**Comment by paulwhite** [comment]
I'll add "Fixes #" in all subsequent requests and also change my verbage to imperative present tense.

I think having JavaScript verification to pop up a modal box with an invalid URL an invalid URL would be cool.

Good catch with the form - I'll update it with the form helper.

**Comment by bboe** [comment]
> I'll add "Fixes #" in all subsequent requests

The pull request description can be edited.

> I think having JavaScript verification to pop up a modal box when an invalid URL is submitted would be cool.

I think you're referring to my question "What do you think is the ideal behavior from the user's perspective when a form that is submitted is not valid?". Could you please quote replies when not replying in the same location the comment was made?

Regarding your comment about a javascript pop-up. Yes, I think that would be fantastic. With that said, how might you do it without javascript?

**Comment by paulwhite** [comment]
> Regarding your comment about a javascript pop-up. Yes, I think that would be fantastic. With that said, how might you do it without javascript?

I think we should send a 302 to that will either point back to the upload form (/images/new), or to an error page.

**Comment by bboe** [comment]
> I think we should send a 302 that will either point back to the upload form (/images/new), or to an error page.

I like the first idea. In fact, we can render the form directly from the `create` method such that (1) the values they filled in are already provided, and (2) errors are displayed on that page (when available).

**Pull request merged**
